version: '3.7'

services:
  metalfs-dev:
    image: metalfs/sdk-base:webpack
    init: true
    command: tail -f /dev/null
    working_dir: /workspace
    environment:
      - DISPLAY=$DISPLAY
    volumes:
      - /tmp/.X11-unix:/tmp/.X11-unix
      - ..:/workspace
    devices:
      - /dev/fuse
    cap_add:
      - SYS_ADMIN
      - SYS_PTRACE
    security_opt:
      - apparmor:unconfined
      - seccomp:unconfined
    # mac_address: XX:XX:XX:XX:XX:XX
